"""
Options for Streamlit widgets.
"""


style_gan_choices = [
    "faces (ffhq slim 256x256)",
    "lsun cats",
    "wildlife",
    "my little pony",
    "grumpy cat",
    "lsun cars",
    "beetles",
    "more abstract art",
    "obama",
    "abstract photos",
    "horse",
    "cakes",
    "car (config-e)",
    "painting faces",
    "butterflies",
    "faces (ffhq config-e)",
    "microscope images",
    "ukiyo-e faces",
    "cifar 10",
    "car (config-f)",
    "wikiart faces",
    "wikiart",
    "figure drawings",
    "cat",
    "anime portraits",
    "anime faces",
    "fireworks",
    "celeba hq faces",
    "textures",
    "fursona",
    "faces (ffhq config-f 512x512)",
    "trypophobia",
    "abstract art",
    "floor plans",
    "ukiyoe faces",
    "cifar 100",
    "panda",
    "church",
    "maps",
    "ffhq faces",
    "lsun bedrooms",
    "pokemon",
    "imagenet",
    "modern art",
    "vases",
    "flowers",
    "faces (ffhq config-e 256x256)",
    "doors",
    "faces (ffhq config-f)",
]
